### ISSUE TITLE
Opam package for compiling with Coq 8.10

### ISSUE THREAD

**Issue by herbelin** [coq-community/qarith-stern-brocot#9]
Hi @Zimmi48, @palmskog : I updated "qarith-stern-brocot" to 8.10.

However, I don't know what procedure you intend to follow:
- I pushed a corresponding tag v8.10.0, thus creating a "release", but I'm unsure I did it the intended way. In particular, I just pushed the tag and did not realize that a proper banner could be also displayed, like it was done for 8.9. I can do it if this is the recommended way to process.
- Do you want me to make an opam, or @palmskog, do you want to make it, the way you did for 8.9?

Note that the contribution "coinductive-reals" depends on "qarith-stern-brocot" and, thus, an opam package is needed for the latter so that the former is opam-installable.

**Comment by Zimmi48** [comment]
Adding notes to the release on GitHub is not required, but would ensure that it is properly displayed when going to the release page. You can do so by going there: https://github.com/coq-community/qarith-stern-brocot/releases/new?tag=v8.10.0

In any case, this is independent of publishing to opam, which either you or @palmskog could take care of.

**Comment by herbelin** [comment]
> You can do so by going there: https://github.com/coq-community/qarith-stern-brocot/releases/new?tag=v8.10.0

Is there a way to let this link be managed in batch mode by a script?

**Comment by Zimmi48** [comment]
We don't have any such script right now but it could be possible in theory. In fact, we are mostly waiting on Coq packages starting to migrate to Dune (when the Coq support gets good enough) so that we can use dune-release to manage the release steps. AFAIU dune-release is able to do the GitHub release creation step (as well as opening a PR in the opam repository).

**Comment by palmskog** [comment]
I annotated the release on GitHub.

**Comment by Zimmi48** [comment]
Should this issue be closed now?

**Comment by herbelin** [comment]
@palmskog : Thanks a lot. @zimmi48: indeed closing then, thanks for hints.
